### ISSUE TITLE
How about Server Renderer of your blog?

### ISSUE THREAD

**Issue by huixiongyu** [mnichangxin/new-blog#1]
If your blog just develop as a Single-Page Application, the post you write may can't be searched from search engines.Do you want to use Nuxt.js?

**Comment by mnichangxin** [comment]
I have not finished yet, but SEO is a problem for the Vue project.

**Comment by mnichangxin** [comment]
> If your blog just develop as a Single-Page Application, the post you write may can't be searched from search engines.Do you want to use Nuxt.js?

I have not finished yet, but SEO is a problem for the Vue project.
